### ISSUE TITLE
Attributing Creative Commons images 

### ISSUE THREAD

**Issue by iamsilvio** [okfde/codefor.de#260]
Attribution is a legal requirement on some images, so it has to be implemented in archetypes and layouts

- Title: The title of the image.
- Author: The name of the creator.
- Source: The URL where the image is hosted (plus optional link to author profile).
- License: The type of Creative Commons license it is available under, including a link to the relevant license.

``` yaml

resources:
- src: 'open-2.jpg'
  description: 'Open neon Schild'
  title: 'red and white open neon signage'
  author: 'Viktor Forgacs'
  author_url: 'https://unsplash.com/@sonance?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'
  license: ''
  source_name: 'Unsplash'
  source_link: 'https://unsplash.com/s/photos/open?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'
  isHeader: true

```
